use JH;

insert into TravelReview (id, title, stars) values (1, 'Angus', 1.5);
insert into TravelReview (id, title, stars) values (2, 'Mingshan', 4.1);
insert into TravelReview (id, title, stars) values (3, 'Tambaú', 4.1);
insert into TravelReview (id, title, stars) values (4, 'Johor Bahru', 2.4);
insert into TravelReview (id, title, stars) values (5, 'El Asintal', 2.9);
insert into TravelReview (id, title, stars) values (6, 'Stockholm', 4.6);
insert into TravelReview (id, title, stars) values (7, 'Venice', 4.2);
insert into TravelReview (id, title, stars) values (8, 'Cantapoy', 1.9);
insert into TravelReview (id, title, stars) values (9, 'Zhongling', 3.4);
insert into TravelReview (id, title, stars) values (10, 'Villa Cañás', 2.6);
insert into TravelReview (id, title, stars) values (11, 'Siemianowice Śląskie', 3.5);
insert into TravelReview (id, title, stars) values (12, 'Cacocum', 2.8);
insert into TravelReview (id, title, stars) values (13, 'Helie', 2.0);
insert into TravelReview (id, title, stars) values (14, 'Verkhnyachka', 2.7);
insert into TravelReview (id, title, stars) values (15, 'Orikhiv', 1.5);
insert into TravelReview (id, title, stars) values (16, 'Roubaix', 1.7);
insert into TravelReview (id, title, stars) values (17, 'Tulcán', 1.9);
insert into TravelReview (id, title, stars) values (18, 'Maglajani', 4.7);
insert into TravelReview (id, title, stars) values (19, 'K’anak’erravan', 2.3);
insert into TravelReview (id, title, stars) values (20, 'Takub', 3.3);
insert into TravelReview (id, title, stars) values (21, 'Poggio di Chiesanuova', 1.1);
insert into TravelReview (id, title, stars) values (22, 'London', 4.7);
insert into TravelReview (id, title, stars) values (23, 'Uusikaupunki', 2.6);
insert into TravelReview (id, title, stars) values (24, 'Xinbu', 4.6);
insert into TravelReview (id, title, stars) values (25, 'Khisarya', 2.1);
insert into TravelReview (id, title, stars) values (26, 'Reshui', 3.5);
insert into TravelReview (id, title, stars) values (27, 'Linhares', 2.2);
insert into TravelReview (id, title, stars) values (28, 'Sarmanovo', 1.3);
insert into TravelReview (id, title, stars) values (29, 'Bystra', 1.5);
insert into TravelReview (id, title, stars) values (30, 'Kangding', 2.8);
insert into TravelReview (id, title, stars) values (31, 'Sandnes', 1.6);
insert into TravelReview (id, title, stars) values (32, 'Shanghu', 2.5);
insert into TravelReview (id, title, stars) values (33, 'Dukuh Kaler', 3.1);
insert into TravelReview (id, title, stars) values (34, 'Kinlough', 2.3);
insert into TravelReview (id, title, stars) values (35, 'Karangranjong', 1.2);
insert into TravelReview (id, title, stars) values (36, 'Bom Despacho', 4.7);
insert into TravelReview (id, title, stars) values (37, 'Sanlifan', 2.5);
insert into TravelReview (id, title, stars) values (38, 'Curibaya', 1.7);
insert into TravelReview (id, title, stars) values (39, 'Funes', 1.4);
insert into TravelReview (id, title, stars) values (40, 'Székesfehérvár', 2.3);
insert into TravelReview (id, title, stars) values (41, 'Calape', 2.0);
insert into TravelReview (id, title, stars) values (42, 'Tangkil', 3.4);
insert into TravelReview (id, title, stars) values (43, 'Vaitape', 1.3);
insert into TravelReview (id, title, stars) values (44, 'Batulayang', 2.4);
insert into TravelReview (id, title, stars) values (45, 'Wang Yang', 4.4);
insert into TravelReview (id, title, stars) values (46, 'Limoeiro de Anadia', 2.8);
insert into TravelReview (id, title, stars) values (47, 'Huazhuang', 3.6);
insert into TravelReview (id, title, stars) values (48, 'Arauco', 1.5);
insert into TravelReview (id, title, stars) values (49, 'Ust’-Ilimsk', 3.5);
insert into TravelReview (id, title, stars) values (50, 'Moulay Abdallah', 3.8);
insert into TravelReview (id, title, stars) values (51, 'Xinji', 4.4);
insert into TravelReview (id, title, stars) values (52, 'El Paso', 3.3);
insert into TravelReview (id, title, stars) values (53, 'Ribeiro', 4.7);
insert into TravelReview (id, title, stars) values (54, 'Sośnie', 1.2);
insert into TravelReview (id, title, stars) values (55, 'Wuling', 5.0);
insert into TravelReview (id, title, stars) values (56, 'Nicosia', 2.6);
insert into TravelReview (id, title, stars) values (57, 'Vouani', 1.7);
insert into TravelReview (id, title, stars) values (58, 'Siewierz', 3.6);
insert into TravelReview (id, title, stars) values (59, 'Magalalag', 4.2);
insert into TravelReview (id, title, stars) values (60, 'Mboursou Léré', 3.9);
insert into TravelReview (id, title, stars) values (61, 'Maych’ew', 3.2);
insert into TravelReview (id, title, stars) values (62, 'Sanjō', 2.6);
insert into TravelReview (id, title, stars) values (63, 'Ganshui', 2.0);
insert into TravelReview (id, title, stars) values (64, 'Zamoskvorech’ye', 1.4);
insert into TravelReview (id, title, stars) values (65, 'Zavolzh’ye', 2.4);
insert into TravelReview (id, title, stars) values (66, 'Xinji', 3.1);
insert into TravelReview (id, title, stars) values (67, 'Jendouba', 3.5);
insert into TravelReview (id, title, stars) values (68, 'Vinkkilä', 1.0);
insert into TravelReview (id, title, stars) values (69, 'Cassilândia', 3.6);
insert into TravelReview (id, title, stars) values (70, 'Jianshan', 3.4);
insert into TravelReview (id, title, stars) values (71, 'Shangcun', 2.6);
insert into TravelReview (id, title, stars) values (72, 'San Jose', 1.2);
insert into TravelReview (id, title, stars) values (73, 'Guifões', 4.9);
insert into TravelReview (id, title, stars) values (74, 'Adh Dhayd', 2.9);
insert into TravelReview (id, title, stars) values (75, 'Boyle', 1.4);
insert into TravelReview (id, title, stars) values (76, 'Novoaleksandrovsk', 4.1);
insert into TravelReview (id, title, stars) values (77, 'Murcia', 2.3);
insert into TravelReview (id, title, stars) values (78, 'Kotawaikabubak', 1.0);
insert into TravelReview (id, title, stars) values (79, 'Mont-de-Marsan', 3.4);
insert into TravelReview (id, title, stars) values (80, 'Tervel', 4.7);
insert into TravelReview (id, title, stars) values (81, 'General Levalle', 3.6);
insert into TravelReview (id, title, stars) values (82, 'Safara', 2.3);
insert into TravelReview (id, title, stars) values (83, 'Watthana Nakhon', 3.3);
insert into TravelReview (id, title, stars) values (84, 'Bal Chirāgh', 3.9);
insert into TravelReview (id, title, stars) values (85, 'Songmuping', 4.8);
insert into TravelReview (id, title, stars) values (86, 'Xishan', 4.5);
insert into TravelReview (id, title, stars) values (87, 'Yanqul', 1.3);
insert into TravelReview (id, title, stars) values (88, 'Miguel Calmon', 4.6);
insert into TravelReview (id, title, stars) values (89, 'El Sombrero', 4.3);
insert into TravelReview (id, title, stars) values (90, 'Banda Layung', 2.5);
insert into TravelReview (id, title, stars) values (91, 'San Lucas', 3.3);
insert into TravelReview (id, title, stars) values (92, 'Tieli', 2.1);
insert into TravelReview (id, title, stars) values (93, 'Guarenas', 3.2);
insert into TravelReview (id, title, stars) values (94, 'Myingyan', 3.7);
insert into TravelReview (id, title, stars) values (95, 'Shijia', 4.5);
insert into TravelReview (id, title, stars) values (96, 'Kefar Tavor', 4.1);
insert into TravelReview (id, title, stars) values (97, 'Dingtao', 4.4);
insert into TravelReview (id, title, stars) values (98, 'Qal‘eh-ye Khvājeh', 2.5);
insert into TravelReview (id, title, stars) values (99, 'Mingyue', 3.9);
insert into TravelReview (id, title, stars) values (100, 'Wakiso', 2.3);
insert into TravelReview (id, title, stars) values (101, 'São Cristóvão', 1.3);
insert into TravelReview (id, title, stars) values (102, 'Rączna', 2.8);
insert into TravelReview (id, title, stars) values (103, 'Tangtou', 3.2);
insert into TravelReview (id, title, stars) values (104, 'Xishanzui', 4.3);
insert into TravelReview (id, title, stars) values (105, 'Fizuli', 1.2);
insert into TravelReview (id, title, stars) values (106, 'Zhendeqiao', 1.5);
insert into TravelReview (id, title, stars) values (107, 'Solnechnyy', 4.9);
insert into TravelReview (id, title, stars) values (108, 'Skopin', 2.8);
insert into TravelReview (id, title, stars) values (109, 'Acopiara', 1.7);
insert into TravelReview (id, title, stars) values (110, 'Santiago', 1.5);
insert into TravelReview (id, title, stars) values (111, 'Tigbao', 2.0);
insert into TravelReview (id, title, stars) values (112, 'As Sūq al Jadīd', 4.8);
insert into TravelReview (id, title, stars) values (113, 'Onitsha', 2.0);
insert into TravelReview (id, title, stars) values (114, 'Sibubuhan', 1.9);
insert into TravelReview (id, title, stars) values (115, 'Matmata', 2.1);
insert into TravelReview (id, title, stars) values (116, 'Navegantes', 4.8);
insert into TravelReview (id, title, stars) values (117, 'Sonsón', 1.1);
insert into TravelReview (id, title, stars) values (118, 'Sumberkertokrajan', 2.6);
insert into TravelReview (id, title, stars) values (119, 'Klimavichy', 5.0);
insert into TravelReview (id, title, stars) values (120, 'Pasirhaur', 3.9);
insert into TravelReview (id, title, stars) values (121, 'Mollebamba', 3.9);
insert into TravelReview (id, title, stars) values (122, 'Siquanpu', 2.7);
insert into TravelReview (id, title, stars) values (123, 'Xifangcheng', 3.2);
insert into TravelReview (id, title, stars) values (124, 'Ráječko', 5.0);
insert into TravelReview (id, title, stars) values (125, 'Sambong', 2.4);
insert into TravelReview (id, title, stars) values (126, 'Granada', 4.6);
insert into TravelReview (id, title, stars) values (127, 'Tsurugi-asahimachi', 3.7);
insert into TravelReview (id, title, stars) values (128, 'Rennes', 4.6);
insert into TravelReview (id, title, stars) values (129, 'Kampokpok', 3.5);
insert into TravelReview (id, title, stars) values (130, 'Leones', 4.5);
insert into TravelReview (id, title, stars) values (131, 'Khulna', 3.2);
insert into TravelReview (id, title, stars) values (132, 'Mnelalete', 1.5);
insert into TravelReview (id, title, stars) values (133, 'Gandzak', 3.6);
insert into TravelReview (id, title, stars) values (134, 'Lý Sơn', 1.2);
insert into TravelReview (id, title, stars) values (135, 'San Miguel', 2.0);
insert into TravelReview (id, title, stars) values (136, 'Fort Worth', 1.2);
insert into TravelReview (id, title, stars) values (137, 'Edineţ', 2.8);
insert into TravelReview (id, title, stars) values (138, 'Pukhavichy', 3.6);
insert into TravelReview (id, title, stars) values (139, 'Boundiali', 4.0);
insert into TravelReview (id, title, stars) values (140, 'Matsubase', 2.9);
insert into TravelReview (id, title, stars) values (141, 'Teresa', 1.1);
insert into TravelReview (id, title, stars) values (142, 'Tanshan', 2.0);
insert into TravelReview (id, title, stars) values (143, 'Donggong', 4.5);
insert into TravelReview (id, title, stars) values (144, 'Macedo de Cavaleiros', 3.0);
insert into TravelReview (id, title, stars) values (145, 'Tulsa', 2.8);
insert into TravelReview (id, title, stars) values (146, 'Xiema', 3.2);
insert into TravelReview (id, title, stars) values (147, 'Tlatah', 1.6);
insert into TravelReview (id, title, stars) values (148, 'Tours', 2.2);
insert into TravelReview (id, title, stars) values (149, 'Canggetelo', 3.2);
insert into TravelReview (id, title, stars) values (150, 'Adolfo Lopez Mateos', 1.1);
insert into TravelReview (id, title, stars) values (151, 'Dammarie-les-Lys', 3.4);
insert into TravelReview (id, title, stars) values (152, 'Miguel Hidalgo', 5.0);
insert into TravelReview (id, title, stars) values (153, 'Gualmatán', 1.2);
insert into TravelReview (id, title, stars) values (154, 'Bailuquan', 3.2);
insert into TravelReview (id, title, stars) values (155, 'Qijing', 1.4);
insert into TravelReview (id, title, stars) values (156, 'Loučovice', 2.0);
insert into TravelReview (id, title, stars) values (157, 'Xunhe', 2.1);
insert into TravelReview (id, title, stars) values (158, 'Ospina', 3.7);
insert into TravelReview (id, title, stars) values (159, 'Gudja', 4.5);
insert into TravelReview (id, title, stars) values (160, 'Watrous', 1.1);
insert into TravelReview (id, title, stars) values (161, 'Turmus‘ayyā', 4.1);
insert into TravelReview (id, title, stars) values (162, 'Shilong', 4.6);
insert into TravelReview (id, title, stars) values (163, 'Pulong Gubat', 1.9);
insert into TravelReview (id, title, stars) values (164, 'Jinping', 5.0);
insert into TravelReview (id, title, stars) values (165, 'Ritchie', 4.2);
insert into TravelReview (id, title, stars) values (166, 'Oslo', 2.5);
insert into TravelReview (id, title, stars) values (167, 'Renfrew', 4.1);
insert into TravelReview (id, title, stars) values (168, 'Chavusy', 3.7);
insert into TravelReview (id, title, stars) values (169, 'Sułów', 3.4);
insert into TravelReview (id, title, stars) values (170, 'Buyende', 5.0);
insert into TravelReview (id, title, stars) values (171, 'Kauhava', 1.5);
insert into TravelReview (id, title, stars) values (172, 'Modakeke', 3.7);
insert into TravelReview (id, title, stars) values (173, 'Itaberaí', 1.4);
insert into TravelReview (id, title, stars) values (174, 'Rochester', 3.7);
insert into TravelReview (id, title, stars) values (175, 'Andekantor', 3.7);
insert into TravelReview (id, title, stars) values (176, 'Anjirmuara', 4.1);
insert into TravelReview (id, title, stars) values (177, 'Crépy-en-Valois', 1.8);
insert into TravelReview (id, title, stars) values (178, 'Tanalt', 1.5);
insert into TravelReview (id, title, stars) values (179, 'Zaoshi', 3.2);
insert into TravelReview (id, title, stars) values (180, 'Kebonkai', 4.7);
insert into TravelReview (id, title, stars) values (181, 'Curry', 3.5);
insert into TravelReview (id, title, stars) values (182, 'Libertad', 4.9);
insert into TravelReview (id, title, stars) values (183, 'Armanāz', 3.0);
insert into TravelReview (id, title, stars) values (184, 'El Soberbio', 2.4);
insert into TravelReview (id, title, stars) values (185, 'Layo', 1.2);
insert into TravelReview (id, title, stars) values (186, 'Weiting', 2.9);
insert into TravelReview (id, title, stars) values (187, 'Ohafia-Ifigh', 4.6);
insert into TravelReview (id, title, stars) values (188, 'København', 1.6);
insert into TravelReview (id, title, stars) values (189, 'Shicha', 4.3);
insert into TravelReview (id, title, stars) values (190, 'Zhexiao', 3.3);
insert into TravelReview (id, title, stars) values (191, 'Chelopech', 1.1);
insert into TravelReview (id, title, stars) values (192, 'Las Tablas', 3.9);
insert into TravelReview (id, title, stars) values (193, 'Al Wardānīn', 3.2);
insert into TravelReview (id, title, stars) values (194, 'Eadestown', 3.1);
insert into TravelReview (id, title, stars) values (195, 'Göteborg', 3.5);
insert into TravelReview (id, title, stars) values (196, 'Luoqi', 2.7);
insert into TravelReview (id, title, stars) values (197, 'Lueng Putu', 2.3);
insert into TravelReview (id, title, stars) values (198, 'Bulag', 1.3);
insert into TravelReview (id, title, stars) values (199, 'Dagsar', 2.6);
insert into TravelReview (id, title, stars) values (200, 'Bazi', 1.9);
insert into TravelReview (id, title, stars) values (201, 'Xingnong', 3.2);
insert into TravelReview (id, title, stars) values (202, 'Tsaghkaber', 3.9);
insert into TravelReview (id, title, stars) values (203, 'Dukuhturi', 2.9);
insert into TravelReview (id, title, stars) values (204, 'Zhangdian', 3.0);
insert into TravelReview (id, title, stars) values (205, 'Montgomery', 3.0);
insert into TravelReview (id, title, stars) values (206, 'Op', 4.2);
insert into TravelReview (id, title, stars) values (207, 'Loket', 3.0);
insert into TravelReview (id, title, stars) values (208, 'Vitoria-Gasteiz', 3.6);
insert into TravelReview (id, title, stars) values (209, 'Chengbei', 1.2);
insert into TravelReview (id, title, stars) values (210, 'Chekmagush', 4.4);
insert into TravelReview (id, title, stars) values (211, 'Staraya Stanitsa', 4.5);
insert into TravelReview (id, title, stars) values (212, 'Ermidas do Sado', 3.0);
insert into TravelReview (id, title, stars) values (213, 'Jackson', 1.1);
insert into TravelReview (id, title, stars) values (214, 'Ad Dīs ash Sharqīyah', 2.9);
insert into TravelReview (id, title, stars) values (215, 'Gedian', 4.6);
insert into TravelReview (id, title, stars) values (216, 'Icó', 4.5);
insert into TravelReview (id, title, stars) values (217, 'Arbeláez', 4.7);
insert into TravelReview (id, title, stars) values (218, 'Claye-Souilly', 1.3);
insert into TravelReview (id, title, stars) values (219, 'Vila Chã de Ourique', 3.3);
insert into TravelReview (id, title, stars) values (220, 'Rucava', 1.3);
insert into TravelReview (id, title, stars) values (221, 'Huogezhuang', 1.9);
insert into TravelReview (id, title, stars) values (222, 'Zhangjiahe', 3.7);
insert into TravelReview (id, title, stars) values (223, 'Huangwei', 4.2);
insert into TravelReview (id, title, stars) values (224, 'El Hamma', 3.5);
insert into TravelReview (id, title, stars) values (225, 'Świecie', 4.5);
insert into TravelReview (id, title, stars) values (226, 'Roshchino', 4.6);
insert into TravelReview (id, title, stars) values (227, 'Lansing', 4.8);
insert into TravelReview (id, title, stars) values (228, 'Huantuo', 4.6);
insert into TravelReview (id, title, stars) values (229, 'Yuli', 2.8);
insert into TravelReview (id, title, stars) values (230, 'Balung Barat', 2.8);
insert into TravelReview (id, title, stars) values (231, 'Yongjiu', 4.5);
insert into TravelReview (id, title, stars) values (232, 'Maunatlala', 1.5);
insert into TravelReview (id, title, stars) values (233, 'Kalisangkrah Lor', 4.0);
insert into TravelReview (id, title, stars) values (234, 'Górzno', 1.9);
insert into TravelReview (id, title, stars) values (235, 'Suai', 3.5);
insert into TravelReview (id, title, stars) values (236, 'Bealanana', 4.3);
insert into TravelReview (id, title, stars) values (237, 'Shangmofang', 3.6);
insert into TravelReview (id, title, stars) values (238, 'Pulau Pinang', 1.3);
insert into TravelReview (id, title, stars) values (239, 'Tsyurupyns’k', 4.7);
insert into TravelReview (id, title, stars) values (240, 'Fayzabad', 4.5);
insert into TravelReview (id, title, stars) values (241, 'Petukhovo', 4.0);
insert into TravelReview (id, title, stars) values (242, 'Maxu', 3.6);
insert into TravelReview (id, title, stars) values (243, 'Anping', 3.3);
insert into TravelReview (id, title, stars) values (244, 'Zhangjiawan', 2.2);
insert into TravelReview (id, title, stars) values (245, 'Sonsón', 3.8);
insert into TravelReview (id, title, stars) values (246, 'Regla', 1.6);
insert into TravelReview (id, title, stars) values (247, 'Les Clayes-sous-Bois', 4.7);
insert into TravelReview (id, title, stars) values (248, 'Manisi', 1.9);
insert into TravelReview (id, title, stars) values (249, 'Jimeta', 4.1);
insert into TravelReview (id, title, stars) values (250, 'Dallas', 2.8);
insert into TravelReview (id, title, stars) values (251, 'Cox’s Bāzār', 2.8);
insert into TravelReview (id, title, stars) values (252, 'Huaquirca', 3.1);
insert into TravelReview (id, title, stars) values (253, 'Surenavan', 3.2);
insert into TravelReview (id, title, stars) values (254, 'Stockholm', 3.0);
insert into TravelReview (id, title, stars) values (255, 'Richmond', 4.5);
insert into TravelReview (id, title, stars) values (256, 'Tanza', 4.8);
insert into TravelReview (id, title, stars) values (257, 'Yuguan', 3.0);
insert into TravelReview (id, title, stars) values (258, 'Nakhon Chai Si', 2.6);
insert into TravelReview (id, title, stars) values (259, 'Malysheva', 3.7);
insert into TravelReview (id, title, stars) values (260, 'Uticyacu', 3.3);
insert into TravelReview (id, title, stars) values (261, 'Suban Jeriji', 4.5);
insert into TravelReview (id, title, stars) values (262, 'Prang Ku', 2.2);
insert into TravelReview (id, title, stars) values (263, 'Xiaojin', 2.9);
insert into TravelReview (id, title, stars) values (264, 'Dzyatlava', 3.2);
insert into TravelReview (id, title, stars) values (265, 'Mundri', 1.6);
insert into TravelReview (id, title, stars) values (266, 'Alamar', 1.2);
insert into TravelReview (id, title, stars) values (267, 'Tengqiao', 1.1);
insert into TravelReview (id, title, stars) values (268, 'Hobart', 2.2);
insert into TravelReview (id, title, stars) values (269, 'Fujikawaguchiko', 3.7);
insert into TravelReview (id, title, stars) values (270, 'København', 2.9);
insert into TravelReview (id, title, stars) values (271, 'Wang Thonglang', 1.2);
insert into TravelReview (id, title, stars) values (272, 'Nantes', 4.1);
insert into TravelReview (id, title, stars) values (273, 'Saint Pierre', 2.8);
insert into TravelReview (id, title, stars) values (274, 'Dzhayrakh', 4.0);
insert into TravelReview (id, title, stars) values (275, 'Wieniawa', 4.1);
insert into TravelReview (id, title, stars) values (276, 'Nagaoka', 3.5);
insert into TravelReview (id, title, stars) values (277, 'Zoumaping', 1.2);
insert into TravelReview (id, title, stars) values (278, 'Bužim', 4.4);
insert into TravelReview (id, title, stars) values (279, 'Pittsburgh', 4.1);
insert into TravelReview (id, title, stars) values (280, 'Ourense', 1.2);
insert into TravelReview (id, title, stars) values (281, 'Jijiang', 2.2);
insert into TravelReview (id, title, stars) values (282, 'Haozhai', 3.7);
insert into TravelReview (id, title, stars) values (283, 'Bachok', 3.2);
insert into TravelReview (id, title, stars) values (284, 'Fenglin', 2.1);
insert into TravelReview (id, title, stars) values (285, 'Petkovci', 4.1);
insert into TravelReview (id, title, stars) values (286, 'Sergokala', 2.0);
insert into TravelReview (id, title, stars) values (287, 'Ciwidara', 3.8);
insert into TravelReview (id, title, stars) values (288, 'Kinlough', 3.8);
insert into TravelReview (id, title, stars) values (289, 'Ghazni', 4.8);
insert into TravelReview (id, title, stars) values (290, 'Mucuri', 2.9);
insert into TravelReview (id, title, stars) values (291, 'Dongbatu', 4.2);
insert into TravelReview (id, title, stars) values (292, 'Martigues', 2.7);
insert into TravelReview (id, title, stars) values (293, 'Sherbrooke', 1.6);
insert into TravelReview (id, title, stars) values (294, 'Bum Bum', 2.8);
insert into TravelReview (id, title, stars) values (295, 'Sungaipuntik', 2.5);
insert into TravelReview (id, title, stars) values (296, 'Bauta', 4.8);
insert into TravelReview (id, title, stars) values (297, 'São Filipe', 1.2);
insert into TravelReview (id, title, stars) values (298, 'Babug', 4.5);
insert into TravelReview (id, title, stars) values (299, 'Komoro', 4.4);
insert into TravelReview (id, title, stars) values (300, 'Zhengmo', 4.2);
insert into TravelReview (id, title, stars) values (301, 'Zhaoxiang', 1.4);
insert into TravelReview (id, title, stars) values (302, 'Hrastnik', 2.1);
insert into TravelReview (id, title, stars) values (303, 'Qijiang', 2.7);
insert into TravelReview (id, title, stars) values (304, 'Krajan', 1.6);
insert into TravelReview (id, title, stars) values (305, 'Masparrito', 4.3);
insert into TravelReview (id, title, stars) values (306, 'Bla', 1.5);
insert into TravelReview (id, title, stars) values (307, 'Washington', 2.4);
insert into TravelReview (id, title, stars) values (308, 'Nanqiu', 2.9);
insert into TravelReview (id, title, stars) values (309, 'Morje', 4.5);
insert into TravelReview (id, title, stars) values (310, 'Nor Yerznka', 4.6);
insert into TravelReview (id, title, stars) values (311, 'Yazykovo', 3.5);
insert into TravelReview (id, title, stars) values (312, 'Qionghai', 3.6);
insert into TravelReview (id, title, stars) values (313, 'Loei', 4.6);
insert into TravelReview (id, title, stars) values (314, 'Zhonghe', 4.3);
insert into TravelReview (id, title, stars) values (315, 'Caidian', 4.9);
insert into TravelReview (id, title, stars) values (316, 'Cabaritan East', 1.8);
insert into TravelReview (id, title, stars) values (317, 'Saumur', 1.2);
insert into TravelReview (id, title, stars) values (318, 'Novoanninskiy', 2.1);
insert into TravelReview (id, title, stars) values (319, 'Primorka', 3.7);
insert into TravelReview (id, title, stars) values (320, 'Piedade', 1.3);
insert into TravelReview (id, title, stars) values (321, 'Songwon', 4.9);
insert into TravelReview (id, title, stars) values (322, 'Al Qurayn', 1.2);
insert into TravelReview (id, title, stars) values (323, 'Maying', 2.3);
insert into TravelReview (id, title, stars) values (324, 'Pāvilosta', 4.6);
insert into TravelReview (id, title, stars) values (325, 'Naḥf', 2.3);
insert into TravelReview (id, title, stars) values (326, 'Adiaké', 2.1);
insert into TravelReview (id, title, stars) values (327, 'El Cocuy', 4.5);
insert into TravelReview (id, title, stars) values (328, 'Ma’an', 3.6);
insert into TravelReview (id, title, stars) values (329, 'Göteborg', 3.2);
insert into TravelReview (id, title, stars) values (330, 'Pandak', 1.5);
insert into TravelReview (id, title, stars) values (331, 'Krasnoye', 3.6);
insert into TravelReview (id, title, stars) values (332, 'Sanyi', 4.8);
insert into TravelReview (id, title, stars) values (333, 'Prakhon Chai', 3.5);
insert into TravelReview (id, title, stars) values (334, 'Santa Lucia', 2.1);
insert into TravelReview (id, title, stars) values (335, 'Nūrābād', 4.5);
insert into TravelReview (id, title, stars) values (336, 'Yelizavetinskaya', 1.7);
insert into TravelReview (id, title, stars) values (337, 'Guolemude', 3.0);
insert into TravelReview (id, title, stars) values (338, 'Jalaud', 3.1);
insert into TravelReview (id, title, stars) values (339, 'Tía Juana', 3.8);
insert into TravelReview (id, title, stars) values (340, 'Paynjuwayn', 3.7);
insert into TravelReview (id, title, stars) values (341, 'Krajan', 1.3);
insert into TravelReview (id, title, stars) values (342, 'Yasothon', 3.7);
insert into TravelReview (id, title, stars) values (343, 'Lokorae', 3.1);
insert into TravelReview (id, title, stars) values (344, 'Las Vegas', 1.9);
insert into TravelReview (id, title, stars) values (345, 'Waishan', 1.2);
insert into TravelReview (id, title, stars) values (346, 'Shangyang', 2.7);
insert into TravelReview (id, title, stars) values (347, 'Annonay', 3.2);
insert into TravelReview (id, title, stars) values (348, 'Tanbu', 2.2);
insert into TravelReview (id, title, stars) values (349, 'Rędziny', 1.8);
insert into TravelReview (id, title, stars) values (350, 'Ágios Matthaíos', 4.7);
insert into TravelReview (id, title, stars) values (351, 'Somerset East', 4.2);
insert into TravelReview (id, title, stars) values (352, 'Padova', 3.9);
insert into TravelReview (id, title, stars) values (353, 'Tamanan', 5.0);
insert into TravelReview (id, title, stars) values (354, 'Tottori', 2.1);
insert into TravelReview (id, title, stars) values (355, 'Ecroignard', 2.2);
insert into TravelReview (id, title, stars) values (356, 'Dianbu', 2.8);
insert into TravelReview (id, title, stars) values (357, 'Heerlen', 2.2);
insert into TravelReview (id, title, stars) values (358, 'Candi Prambanan', 1.5);
insert into TravelReview (id, title, stars) values (359, 'Matangpayang', 3.7);
insert into TravelReview (id, title, stars) values (360, 'Łobodno', 4.7);
insert into TravelReview (id, title, stars) values (361, 'Log', 3.7);
insert into TravelReview (id, title, stars) values (362, 'Alma', 2.0);
insert into TravelReview (id, title, stars) values (363, 'Shangqing', 1.5);
insert into TravelReview (id, title, stars) values (364, 'Jiekou', 3.6);
insert into TravelReview (id, title, stars) values (365, 'Postřekov', 2.3);
insert into TravelReview (id, title, stars) values (366, 'Wenqiao', 2.3);
insert into TravelReview (id, title, stars) values (367, 'Wolong', 1.6);
insert into TravelReview (id, title, stars) values (368, 'Xicheng', 3.8);
insert into TravelReview (id, title, stars) values (369, 'Nîmes', 4.8);
insert into TravelReview (id, title, stars) values (370, 'Phitsanulok', 3.4);
insert into TravelReview (id, title, stars) values (371, 'Yuanqiao', 3.7);
insert into TravelReview (id, title, stars) values (372, 'Yanhe', 1.4);
insert into TravelReview (id, title, stars) values (373, 'Hejia', 4.3);
insert into TravelReview (id, title, stars) values (374, 'Mashtūl as Sūq', 4.5);
insert into TravelReview (id, title, stars) values (375, 'Mukdahan', 2.4);
insert into TravelReview (id, title, stars) values (376, 'Burns Lake', 3.9);
insert into TravelReview (id, title, stars) values (377, 'Kawage', 2.9);
insert into TravelReview (id, title, stars) values (378, 'Pizarrete', 3.7);
insert into TravelReview (id, title, stars) values (379, 'Bayog', 2.2);
insert into TravelReview (id, title, stars) values (380, 'Carrascal', 3.7);
insert into TravelReview (id, title, stars) values (381, 'Abiko', 1.2);
insert into TravelReview (id, title, stars) values (382, 'Duotian', 1.2);
insert into TravelReview (id, title, stars) values (383, 'Longkou', 1.7);
insert into TravelReview (id, title, stars) values (384, 'Severnyy', 1.1);
insert into TravelReview (id, title, stars) values (385, 'Bratsk', 4.8);
insert into TravelReview (id, title, stars) values (386, 'Charxin', 2.5);
insert into TravelReview (id, title, stars) values (387, 'Srunikrajan', 2.7);
insert into TravelReview (id, title, stars) values (388, 'Yara', 1.1);
insert into TravelReview (id, title, stars) values (389, 'Capâo Bonito', 3.2);
insert into TravelReview (id, title, stars) values (390, 'Dailekh', 2.5);
insert into TravelReview (id, title, stars) values (391, 'Darungan', 1.1);
insert into TravelReview (id, title, stars) values (392, 'Kut Chap', 3.9);
insert into TravelReview (id, title, stars) values (393, 'Dongjie', 3.0);
insert into TravelReview (id, title, stars) values (394, 'Norrtälje', 1.6);
insert into TravelReview (id, title, stars) values (395, 'Sietesz', 3.4);
insert into TravelReview (id, title, stars) values (396, 'Dingchang', 2.5);
insert into TravelReview (id, title, stars) values (397, 'Bay-ang', 2.6);
insert into TravelReview (id, title, stars) values (398, 'Siepraw', 2.1);
insert into TravelReview (id, title, stars) values (399, 'Głogówek', 4.2);
insert into TravelReview (id, title, stars) values (400, 'Tashanta', 2.7);
insert into TravelReview (id, title, stars) values (401, 'Manturovo', 1.1);
insert into TravelReview (id, title, stars) values (402, 'Libacao', 3.3);
insert into TravelReview (id, title, stars) values (403, 'Daqiao', 4.6);
insert into TravelReview (id, title, stars) values (404, 'Haninge', 4.4);
insert into TravelReview (id, title, stars) values (405, 'Shenji', 2.7);
insert into TravelReview (id, title, stars) values (406, 'Strančice', 4.8);
insert into TravelReview (id, title, stars) values (407, 'Fauske', 1.6);
insert into TravelReview (id, title, stars) values (408, 'San Luis', 1.8);
insert into TravelReview (id, title, stars) values (409, 'Jinchuan', 2.5);
insert into TravelReview (id, title, stars) values (410, 'Prantaan', 2.6);
insert into TravelReview (id, title, stars) values (411, 'Orizari', 2.9);
insert into TravelReview (id, title, stars) values (412, 'Tongjing', 1.3);
insert into TravelReview (id, title, stars) values (413, 'Macklin', 2.1);
insert into TravelReview (id, title, stars) values (414, 'Nagornyy', 4.2);
insert into TravelReview (id, title, stars) values (415, 'Drammen', 4.5);
insert into TravelReview (id, title, stars) values (416, 'Karaidel’', 4.6);
insert into TravelReview (id, title, stars) values (417, 'Đức Phong', 4.9);
insert into TravelReview (id, title, stars) values (418, 'Prakhon Chai', 4.6);
insert into TravelReview (id, title, stars) values (419, 'Taiping', 4.3);
insert into TravelReview (id, title, stars) values (420, 'Al Badārī', 3.9);
insert into TravelReview (id, title, stars) values (421, 'Kedungbanteng Krajan', 4.4);
insert into TravelReview (id, title, stars) values (422, 'Konispol', 4.3);
insert into TravelReview (id, title, stars) values (423, 'Sertolovo', 3.7);
insert into TravelReview (id, title, stars) values (424, 'Tarragona', 3.1);
insert into TravelReview (id, title, stars) values (425, 'Yushu', 1.3);
insert into TravelReview (id, title, stars) values (426, 'Yŏnan-ŭp', 3.5);
insert into TravelReview (id, title, stars) values (427, 'Dobrzeń Wielki', 3.8);
insert into TravelReview (id, title, stars) values (428, 'Kitahama', 3.1);
insert into TravelReview (id, title, stars) values (429, 'Ban Thai Tan', 4.0);
insert into TravelReview (id, title, stars) values (430, 'Titao', 3.2);
insert into TravelReview (id, title, stars) values (431, 'El Zapote', 4.5);
insert into TravelReview (id, title, stars) values (432, 'Bambari', 3.3);
insert into TravelReview (id, title, stars) values (433, 'Dulles', 1.2);
insert into TravelReview (id, title, stars) values (434, 'Borova', 4.9);
insert into TravelReview (id, title, stars) values (435, 'Huancheng', 4.2);
insert into TravelReview (id, title, stars) values (436, 'Al Bāriqīyah', 2.9);
insert into TravelReview (id, title, stars) values (437, 'Bolaoit', 2.9);
insert into TravelReview (id, title, stars) values (438, 'Antioquia', 2.0);
insert into TravelReview (id, title, stars) values (439, 'Akita', 1.8);
insert into TravelReview (id, title, stars) values (440, 'Podbrdo', 4.8);
insert into TravelReview (id, title, stars) values (441, 'San Felipe', 5.0);
insert into TravelReview (id, title, stars) values (442, 'Lilla Edet', 3.9);
insert into TravelReview (id, title, stars) values (443, 'Butha-Buthe', 3.4);
insert into TravelReview (id, title, stars) values (444, 'Saint-André-Avellin', 1.8);
insert into TravelReview (id, title, stars) values (445, 'Canhestros', 3.8);
insert into TravelReview (id, title, stars) values (446, 'Baisha', 3.5);
insert into TravelReview (id, title, stars) values (447, 'Besuki Dua', 4.5);
insert into TravelReview (id, title, stars) values (448, 'København', 1.1);
insert into TravelReview (id, title, stars) values (449, 'Bektemir', 2.2);
insert into TravelReview (id, title, stars) values (450, 'Paris La Défense', 3.9);
insert into TravelReview (id, title, stars) values (451, 'Jiesheng', 4.4);
insert into TravelReview (id, title, stars) values (452, 'General Manuel J. Campos', 2.3);
insert into TravelReview (id, title, stars) values (453, 'Fangli', 1.9);
insert into TravelReview (id, title, stars) values (454, 'Goyang-si', 3.1);
insert into TravelReview (id, title, stars) values (455, 'Providence', 3.8);
insert into TravelReview (id, title, stars) values (456, 'Portela', 3.6);
insert into TravelReview (id, title, stars) values (457, 'Mochishche', 2.0);
insert into TravelReview (id, title, stars) values (458, 'Leer', 2.4);
insert into TravelReview (id, title, stars) values (459, 'Baicun', 2.2);
insert into TravelReview (id, title, stars) values (460, 'Kalembutillu', 3.9);
insert into TravelReview (id, title, stars) values (461, 'Russkiy', 3.7);
insert into TravelReview (id, title, stars) values (462, 'Kuryłówka', 3.4);
insert into TravelReview (id, title, stars) values (463, 'Stepove', 1.7);
insert into TravelReview (id, title, stars) values (464, 'Býšť', 4.5);
insert into TravelReview (id, title, stars) values (465, 'Pangkajene', 3.1);
insert into TravelReview (id, title, stars) values (466, 'São Miguel do Rio Torto', 4.0);
insert into TravelReview (id, title, stars) values (467, 'Tiwi', 2.2);
insert into TravelReview (id, title, stars) values (468, 'Vista Alegre', 4.7);
insert into TravelReview (id, title, stars) values (469, 'Santa Cruz', 4.1);
insert into TravelReview (id, title, stars) values (470, 'Malikisi', 4.1);
insert into TravelReview (id, title, stars) values (471, 'Dengok', 2.6);
insert into TravelReview (id, title, stars) values (472, 'Gómfoi', 3.9);
insert into TravelReview (id, title, stars) values (473, 'Xianxi', 3.2);
insert into TravelReview (id, title, stars) values (474, 'Wenwuba', 4.2);
insert into TravelReview (id, title, stars) values (475, 'Matsue-shi', 3.8);
insert into TravelReview (id, title, stars) values (476, 'Futu', 4.8);
insert into TravelReview (id, title, stars) values (477, 'Calvão', 4.9);
insert into TravelReview (id, title, stars) values (478, 'Khvalovo', 3.2);
insert into TravelReview (id, title, stars) values (479, 'Tebara', 1.0);
insert into TravelReview (id, title, stars) values (480, 'San Rafael Arriba', 4.0);
insert into TravelReview (id, title, stars) values (481, 'Al Matlīn', 3.1);
insert into TravelReview (id, title, stars) values (482, 'Saint-Lin-Laurentides', 3.6);
insert into TravelReview (id, title, stars) values (483, 'Hamamatsu', 3.6);
insert into TravelReview (id, title, stars) values (484, 'Loukhi', 1.4);
insert into TravelReview (id, title, stars) values (485, 'Đức Phong', 4.6);
insert into TravelReview (id, title, stars) values (486, 'Tha Yang', 2.5);
insert into TravelReview (id, title, stars) values (487, 'Becerril', 2.6);
insert into TravelReview (id, title, stars) values (488, 'Aix-en-Provence', 4.4);
insert into TravelReview (id, title, stars) values (489, 'Murmashi', 4.8);
insert into TravelReview (id, title, stars) values (490, 'Vohibinany', 2.8);
insert into TravelReview (id, title, stars) values (491, 'Jengglungharjo', 1.6);
insert into TravelReview (id, title, stars) values (492, 'Czernice Borowe', 2.8);
insert into TravelReview (id, title, stars) values (493, 'Talovyy', 2.0);
insert into TravelReview (id, title, stars) values (494, 'Kafr Takhārīm', 4.7);
insert into TravelReview (id, title, stars) values (495, 'Aguasay', 4.3);
insert into TravelReview (id, title, stars) values (496, 'Bantarpanjang', 4.4);
insert into TravelReview (id, title, stars) values (497, 'Oeleon', 1.6);
insert into TravelReview (id, title, stars) values (498, 'Kax', 4.6);
insert into TravelReview (id, title, stars) values (499, 'La Rochelle', 1.9);
insert into TravelReview (id, title, stars) values (500, 'Vnukovo', 4.3);
insert into TravelReview (id, title, stars) values (501, 'Pangascasan', 4.1);
insert into TravelReview (id, title, stars) values (502, 'Bethel Town', 3.2);
insert into TravelReview (id, title, stars) values (503, 'Linglong', 2.6);
insert into TravelReview (id, title, stars) values (504, 'Grand Rapids', 2.2);
insert into TravelReview (id, title, stars) values (505, 'Changfa', 1.5);
insert into TravelReview (id, title, stars) values (506, 'Wotan', 3.8);
insert into TravelReview (id, title, stars) values (507, 'Vaiusu', 2.3);
insert into TravelReview (id, title, stars) values (508, 'Bungtiang Barat', 2.7);
insert into TravelReview (id, title, stars) values (509, 'Feliciano', 2.8);
insert into TravelReview (id, title, stars) values (510, 'Cincinnati', 1.3);
insert into TravelReview (id, title, stars) values (511, 'Mafang', 3.4);
insert into TravelReview (id, title, stars) values (512, 'Banyue', 4.8);
insert into TravelReview (id, title, stars) values (513, 'Pereyaslav-Khmel’nyts’kyy', 1.5);
insert into TravelReview (id, title, stars) values (514, 'Cacequi', 4.5);
insert into TravelReview (id, title, stars) values (515, 'Azaruja', 1.4);
insert into TravelReview (id, title, stars) values (516, 'Ōkawara', 4.4);
insert into TravelReview (id, title, stars) values (517, 'Huangduobu', 2.4);
insert into TravelReview (id, title, stars) values (518, 'Donglai', 2.4);
insert into TravelReview (id, title, stars) values (519, '‘Alāqahdārī Gēlān', 3.2);
insert into TravelReview (id, title, stars) values (520, 'Macamic', 2.0);
insert into TravelReview (id, title, stars) values (521, 'Siao', 1.7);
insert into TravelReview (id, title, stars) values (522, 'Hrob', 1.8);
insert into TravelReview (id, title, stars) values (523, 'Ko Si Chang', 3.1);
insert into TravelReview (id, title, stars) values (524, 'Middelburg', 4.2);
insert into TravelReview (id, title, stars) values (525, 'Shangani', 1.2);
insert into TravelReview (id, title, stars) values (526, 'Louriceira', 3.7);
insert into TravelReview (id, title, stars) values (527, 'Osiek', 2.6);
insert into TravelReview (id, title, stars) values (528, 'Łomianki', 1.5);
insert into TravelReview (id, title, stars) values (529, 'Saidpur', 1.1);
insert into TravelReview (id, title, stars) values (530, 'Yushu', 2.0);
insert into TravelReview (id, title, stars) values (531, 'Vila Flor', 3.8);
insert into TravelReview (id, title, stars) values (532, 'Tagog', 5.0);
insert into TravelReview (id, title, stars) values (533, 'Dingdian', 2.8);
insert into TravelReview (id, title, stars) values (534, 'Yandang', 2.8);
insert into TravelReview (id, title, stars) values (535, 'Abashiri', 2.2);
insert into TravelReview (id, title, stars) values (536, 'Odivelas', 2.3);
insert into TravelReview (id, title, stars) values (537, 'Brodokalmak', 2.8);
insert into TravelReview (id, title, stars) values (538, 'Amphoe Sikhiu', 1.9);
insert into TravelReview (id, title, stars) values (539, 'Tlogowungu', 4.5);
insert into TravelReview (id, title, stars) values (540, 'Antsohimbondrona', 3.1);
insert into TravelReview (id, title, stars) values (541, 'Duobao', 2.9);
insert into TravelReview (id, title, stars) values (542, 'Karlstad', 1.7);
insert into TravelReview (id, title, stars) values (543, 'San Antonio', 1.3);
insert into TravelReview (id, title, stars) values (544, 'Staroderevyankovskaya', 1.7);
insert into TravelReview (id, title, stars) values (545, 'Linghu', 4.4);
insert into TravelReview (id, title, stars) values (546, 'Descalvado', 2.7);
insert into TravelReview (id, title, stars) values (547, 'Yongxing', 2.0);
insert into TravelReview (id, title, stars) values (548, 'Likino-Dulevo', 4.3);
insert into TravelReview (id, title, stars) values (549, 'Songkeng', 4.9);
insert into TravelReview (id, title, stars) values (550, 'Ban Thaen', 3.3);
insert into TravelReview (id, title, stars) values (551, 'Haninge', 2.3);
insert into TravelReview (id, title, stars) values (552, 'Arapongas', 3.3);
insert into TravelReview (id, title, stars) values (553, 'Floriana', 4.1);
insert into TravelReview (id, title, stars) values (554, 'Az Zubaydāt', 4.2);
insert into TravelReview (id, title, stars) values (555, 'Göteborg', 2.5);
insert into TravelReview (id, title, stars) values (556, 'Vienne', 4.9);
insert into TravelReview (id, title, stars) values (557, 'Cervantes', 1.7);
insert into TravelReview (id, title, stars) values (558, 'Suizhou', 4.3);
insert into TravelReview (id, title, stars) values (559, 'Winnipeg', 3.2);
insert into TravelReview (id, title, stars) values (560, 'Klenica', 4.3);
insert into TravelReview (id, title, stars) values (561, 'Venda Nova', 1.2);
insert into TravelReview (id, title, stars) values (562, 'Trảng Bom', 1.4);
insert into TravelReview (id, title, stars) values (563, 'Zhaolingpu', 1.7);
insert into TravelReview (id, title, stars) values (564, 'Lianyi', 4.8);
insert into TravelReview (id, title, stars) values (565, 'Tafo', 4.6);
insert into TravelReview (id, title, stars) values (566, 'Shyroke', 1.5);
insert into TravelReview (id, title, stars) values (567, 'Ribas do Rio Pardo', 4.3);
insert into TravelReview (id, title, stars) values (568, 'Santa Maria', 2.5);
insert into TravelReview (id, title, stars) values (569, 'Foshan', 3.6);
insert into TravelReview (id, title, stars) values (570, 'Aguitu', 1.9);
insert into TravelReview (id, title, stars) values (571, 'Quinipot', 3.9);
insert into TravelReview (id, title, stars) values (572, 'Alquerubim', 1.1);
insert into TravelReview (id, title, stars) values (573, 'Gamay', 3.3);
insert into TravelReview (id, title, stars) values (574, 'Solo', 2.4);
insert into TravelReview (id, title, stars) values (575, 'Bodiosa a Velha', 4.5);
insert into TravelReview (id, title, stars) values (576, 'Titiakar', 4.4);
insert into TravelReview (id, title, stars) values (577, 'Kraśnik', 4.9);
insert into TravelReview (id, title, stars) values (578, 'Puerto Montt', 1.2);
insert into TravelReview (id, title, stars) values (579, 'Gunungputri', 2.9);
insert into TravelReview (id, title, stars) values (580, 'Karano', 3.1);
insert into TravelReview (id, title, stars) values (581, 'Gahe', 3.5);
insert into TravelReview (id, title, stars) values (582, 'Yishui', 1.2);
insert into TravelReview (id, title, stars) values (583, 'Krzyżanowice', 4.5);
insert into TravelReview (id, title, stars) values (584, 'Huangli', 2.9);
insert into TravelReview (id, title, stars) values (585, 'Apaga', 2.6);
insert into TravelReview (id, title, stars) values (586, 'Batken', 2.9);
insert into TravelReview (id, title, stars) values (587, 'Fenjie', 4.4);
insert into TravelReview (id, title, stars) values (588, 'Lyudinovo', 3.1);
insert into TravelReview (id, title, stars) values (589, 'Galveias', 2.0);
insert into TravelReview (id, title, stars) values (590, 'Sulahan', 4.3);
insert into TravelReview (id, title, stars) values (591, 'Paris 19', 1.6);
insert into TravelReview (id, title, stars) values (592, 'Město Albrechtice', 3.2);
insert into TravelReview (id, title, stars) values (593, 'Quintãs', 4.4);
insert into TravelReview (id, title, stars) values (594, 'Porlamar', 3.4);
insert into TravelReview (id, title, stars) values (595, 'Avignon', 4.6);
insert into TravelReview (id, title, stars) values (596, 'Jahrom', 3.0);
insert into TravelReview (id, title, stars) values (597, 'Constantia', 4.0);
insert into TravelReview (id, title, stars) values (598, 'Dongjiao', 4.8);
insert into TravelReview (id, title, stars) values (599, 'Jiaotang', 4.6);
insert into TravelReview (id, title, stars) values (600, 'Dikou', 3.6);
insert into TravelReview (id, title, stars) values (601, 'Pār Naogaon', 3.8);
insert into TravelReview (id, title, stars) values (602, 'Kawangohari', 3.6);
insert into TravelReview (id, title, stars) values (603, 'San Guillermo', 4.2);
insert into TravelReview (id, title, stars) values (604, 'Panaitólion', 1.3);
insert into TravelReview (id, title, stars) values (605, 'Wonokerso', 4.9);
insert into TravelReview (id, title, stars) values (606, 'Guanxi', 3.9);
insert into TravelReview (id, title, stars) values (607, 'Nakamura', 2.9);
insert into TravelReview (id, title, stars) values (608, 'Armenia', 1.9);
insert into TravelReview (id, title, stars) values (609, 'Pushkino', 4.6);
insert into TravelReview (id, title, stars) values (610, 'Uijeongbu-si', 4.5);
insert into TravelReview (id, title, stars) values (611, 'Huanshi', 2.4);
insert into TravelReview (id, title, stars) values (612, 'Jati', 2.6);
insert into TravelReview (id, title, stars) values (613, 'Colmar', 2.1);
insert into TravelReview (id, title, stars) values (614, 'Cakungsari', 4.0);
insert into TravelReview (id, title, stars) values (615, 'Kingston', 4.0);
insert into TravelReview (id, title, stars) values (616, 'Katagum', 1.2);
insert into TravelReview (id, title, stars) values (617, 'Cusco', 2.5);
insert into TravelReview (id, title, stars) values (618, 'Hägersten', 4.9);
insert into TravelReview (id, title, stars) values (619, 'Cilangkap', 3.3);
insert into TravelReview (id, title, stars) values (620, 'Nova Friburgo', 1.9);
insert into TravelReview (id, title, stars) values (621, 'Kleszczów', 2.1);
insert into TravelReview (id, title, stars) values (622, 'Picos', 1.2);
insert into TravelReview (id, title, stars) values (623, 'Panevėžys', 4.2);
insert into TravelReview (id, title, stars) values (624, 'Xinsheng', 3.3);
insert into TravelReview (id, title, stars) values (625, 'Lahishyn', 3.0);
insert into TravelReview (id, title, stars) values (626, 'Haligue', 1.3);
insert into TravelReview (id, title, stars) values (627, 'Sidi Amar', 1.4);
insert into TravelReview (id, title, stars) values (628, 'Koszarawa', 2.0);
insert into TravelReview (id, title, stars) values (629, 'Drásov', 2.2);
insert into TravelReview (id, title, stars) values (630, 'Kampong Cham', 3.7);
insert into TravelReview (id, title, stars) values (631, 'Binafun', 2.2);
insert into TravelReview (id, title, stars) values (632, 'Tengrela', 3.7);
insert into TravelReview (id, title, stars) values (633, 'Pira', 4.3);
insert into TravelReview (id, title, stars) values (634, 'Iitti', 3.0);
insert into TravelReview (id, title, stars) values (635, 'Miaogou', 2.8);
insert into TravelReview (id, title, stars) values (636, 'Ovsyanka', 3.1);
insert into TravelReview (id, title, stars) values (637, 'Dumingag', 1.8);
insert into TravelReview (id, title, stars) values (638, 'Dubna', 4.8);
insert into TravelReview (id, title, stars) values (639, 'Mae Hi', 2.1);
insert into TravelReview (id, title, stars) values (640, 'Sviblovo', 2.9);
insert into TravelReview (id, title, stars) values (641, 'Rathangan', 1.5);
insert into TravelReview (id, title, stars) values (642, 'Jeberos', 4.1);
insert into TravelReview (id, title, stars) values (643, 'Barakī Barak', 3.6);
insert into TravelReview (id, title, stars) values (644, 'Spassk', 2.2);
insert into TravelReview (id, title, stars) values (645, 'Shuangfeng', 2.9);
insert into TravelReview (id, title, stars) values (646, 'Gostilitsy', 4.5);
insert into TravelReview (id, title, stars) values (647, 'Rimbo', 1.2);
insert into TravelReview (id, title, stars) values (648, 'Youwei', 4.5);
insert into TravelReview (id, title, stars) values (649, 'Cartagena', 1.2);
insert into TravelReview (id, title, stars) values (650, 'Aoji-ri', 1.4);
insert into TravelReview (id, title, stars) values (651, 'Geta', 2.7);
insert into TravelReview (id, title, stars) values (652, 'Sacramento', 2.4);
insert into TravelReview (id, title, stars) values (653, 'Yangsan', 3.2);
insert into TravelReview (id, title, stars) values (654, 'Pontevedra', 3.6);
insert into TravelReview (id, title, stars) values (655, 'Tinghir', 4.1);
insert into TravelReview (id, title, stars) values (656, 'Baie-D''Urfé', 3.9);
insert into TravelReview (id, title, stars) values (657, 'Huangzhai', 2.1);
insert into TravelReview (id, title, stars) values (658, 'Changning', 1.6);
insert into TravelReview (id, title, stars) values (659, 'Padang', 2.6);
insert into TravelReview (id, title, stars) values (660, 'Mangai', 3.4);
insert into TravelReview (id, title, stars) values (661, 'Barbalha', 2.3);
insert into TravelReview (id, title, stars) values (662, 'Birendranagar', 3.3);
insert into TravelReview (id, title, stars) values (663, 'Krapivna', 1.7);
insert into TravelReview (id, title, stars) values (664, 'Coruripe', 4.7);
insert into TravelReview (id, title, stars) values (665, 'Grubišno Polje', 4.5);
insert into TravelReview (id, title, stars) values (666, 'Ash Shaḩānīyah', 1.7);
insert into TravelReview (id, title, stars) values (667, 'Boli', 3.5);
insert into TravelReview (id, title, stars) values (668, 'Priekulė', 3.2);
insert into TravelReview (id, title, stars) values (669, 'Hacı Zeynalabdin', 2.2);
insert into TravelReview (id, title, stars) values (670, 'La Victoria', 1.5);
insert into TravelReview (id, title, stars) values (671, 'Kut Chap', 2.0);
insert into TravelReview (id, title, stars) values (672, 'Lazaro Cardenas', 4.3);
insert into TravelReview (id, title, stars) values (673, 'Jaguarari', 2.8);
insert into TravelReview (id, title, stars) values (674, 'Krzyżanów', 4.1);
insert into TravelReview (id, title, stars) values (675, 'Martapura', 1.8);
insert into TravelReview (id, title, stars) values (676, 'Hainan', 1.7);
insert into TravelReview (id, title, stars) values (677, 'Klagenfurt am Wörthersee', 1.3);
insert into TravelReview (id, title, stars) values (678, 'Barengkok Hilir', 2.0);
insert into TravelReview (id, title, stars) values (679, 'Aldeia da Piedade', 1.9);
insert into TravelReview (id, title, stars) values (680, 'Moquegua', 2.9);
insert into TravelReview (id, title, stars) values (681, 'Dobre', 3.5);
insert into TravelReview (id, title, stars) values (682, 'Tocota', 2.1);
insert into TravelReview (id, title, stars) values (683, 'Panaoti', 4.8);
insert into TravelReview (id, title, stars) values (684, 'Phúc Yên', 3.8);
insert into TravelReview (id, title, stars) values (685, 'Apucarana', 4.7);
insert into TravelReview (id, title, stars) values (686, 'Ungheni', 1.2);
insert into TravelReview (id, title, stars) values (687, 'Toshkivka', 2.0);
insert into TravelReview (id, title, stars) values (688, 'Dębe Wielkie', 2.7);
insert into TravelReview (id, title, stars) values (689, 'Hidalgo', 1.5);
insert into TravelReview (id, title, stars) values (690, 'Santo Domingo Este', 1.8);
insert into TravelReview (id, title, stars) values (691, 'San Lorenzo de Esmeraldas', 3.3);
insert into TravelReview (id, title, stars) values (692, 'Dengzhou', 2.4);
insert into TravelReview (id, title, stars) values (693, 'Ribeirão Pires', 4.1);
insert into TravelReview (id, title, stars) values (694, 'Dezhou', 2.4);
insert into TravelReview (id, title, stars) values (695, 'Pompéu', 2.6);
insert into TravelReview (id, title, stars) values (696, 'Carvalho', 2.2);
insert into TravelReview (id, title, stars) values (697, 'Uvarovo', 4.2);
insert into TravelReview (id, title, stars) values (698, 'La Rochelle', 1.3);
insert into TravelReview (id, title, stars) values (699, 'Panalingaan', 1.1);
insert into TravelReview (id, title, stars) values (700, 'Villa Allende', 3.8);
insert into TravelReview (id, title, stars) values (701, 'Bordeaux', 4.8);
insert into TravelReview (id, title, stars) values (702, 'Duba', 4.4);
insert into TravelReview (id, title, stars) values (703, 'Aoqian', 2.3);
insert into TravelReview (id, title, stars) values (704, 'La Libertad', 4.8);
insert into TravelReview (id, title, stars) values (705, 'Chongqing', 3.5);
insert into TravelReview (id, title, stars) values (706, 'Arteche', 3.8);
insert into TravelReview (id, title, stars) values (707, 'Liushikou', 4.7);
insert into TravelReview (id, title, stars) values (708, 'Hüremt', 2.5);
insert into TravelReview (id, title, stars) values (709, 'Angoulême', 1.9);
insert into TravelReview (id, title, stars) values (710, 'Västra Frölunda', 3.7);
insert into TravelReview (id, title, stars) values (711, 'Kirovgrad', 3.4);
insert into TravelReview (id, title, stars) values (712, 'Hongkeli', 1.5);
insert into TravelReview (id, title, stars) values (713, 'Misasi', 1.6);
insert into TravelReview (id, title, stars) values (714, 'Pacaembu', 1.7);
insert into TravelReview (id, title, stars) values (715, 'Kipini', 3.6);
insert into TravelReview (id, title, stars) values (716, 'Novoye Leushino', 3.5);
insert into TravelReview (id, title, stars) values (717, 'Belozërsk', 3.4);
insert into TravelReview (id, title, stars) values (718, 'Heredia', 2.5);
insert into TravelReview (id, title, stars) values (719, 'Fornos', 4.3);
insert into TravelReview (id, title, stars) values (720, 'Kurchaloy', 2.5);
insert into TravelReview (id, title, stars) values (721, 'Balagon', 4.1);
insert into TravelReview (id, title, stars) values (722, 'Pontevedra', 3.8);
insert into TravelReview (id, title, stars) values (723, 'Akureyri', 4.9);
insert into TravelReview (id, title, stars) values (724, 'Bo Phloi', 4.4);
insert into TravelReview (id, title, stars) values (725, 'Masoli', 4.7);
insert into TravelReview (id, title, stars) values (726, 'Luozhou', 2.4);
insert into TravelReview (id, title, stars) values (727, 'Zaïo', 2.5);
insert into TravelReview (id, title, stars) values (728, 'Wufu', 2.8);
insert into TravelReview (id, title, stars) values (729, 'Maguwon', 2.4);
insert into TravelReview (id, title, stars) values (730, 'Zwierzyń', 3.6);
insert into TravelReview (id, title, stars) values (731, 'Tayu', 1.8);
insert into TravelReview (id, title, stars) values (732, 'Krasnyy Klyuch', 3.6);
insert into TravelReview (id, title, stars) values (733, 'Paranaíba', 3.2);
insert into TravelReview (id, title, stars) values (734, 'Tomakomai', 2.3);
insert into TravelReview (id, title, stars) values (735, 'Longwei', 1.2);
insert into TravelReview (id, title, stars) values (736, 'Alqueva', 2.8);
insert into TravelReview (id, title, stars) values (737, 'Baton Rouge', 3.3);
insert into TravelReview (id, title, stars) values (738, 'Starychi', 3.3);
insert into TravelReview (id, title, stars) values (739, 'Trondheim', 1.3);
insert into TravelReview (id, title, stars) values (740, 'Gongdanglegi Kulon', 4.4);
insert into TravelReview (id, title, stars) values (741, 'Karolinka', 2.8);
insert into TravelReview (id, title, stars) values (742, 'Sembon', 3.6);
insert into TravelReview (id, title, stars) values (743, 'Ōbu', 2.0);
insert into TravelReview (id, title, stars) values (744, 'Thủ Thừa', 1.9);
insert into TravelReview (id, title, stars) values (745, 'Dijon', 2.3);
insert into TravelReview (id, title, stars) values (746, 'Alingsås', 3.6);
insert into TravelReview (id, title, stars) values (747, 'São Carlos', 4.1);
insert into TravelReview (id, title, stars) values (748, 'Port Loko', 4.6);
insert into TravelReview (id, title, stars) values (749, 'Kampinos', 4.3);
insert into TravelReview (id, title, stars) values (750, 'Soavinandriana', 2.5);
insert into TravelReview (id, title, stars) values (751, 'Golem', 1.9);
insert into TravelReview (id, title, stars) values (752, 'Żychlin', 3.0);
insert into TravelReview (id, title, stars) values (753, 'Itabuna', 2.4);
insert into TravelReview (id, title, stars) values (754, 'Ko Chan', 1.3);
insert into TravelReview (id, title, stars) values (755, 'Kitami', 4.9);
insert into TravelReview (id, title, stars) values (756, 'Puger', 2.4);
insert into TravelReview (id, title, stars) values (757, 'Lalapanzi', 3.9);
insert into TravelReview (id, title, stars) values (758, 'Jurovski Dol', 3.8);
insert into TravelReview (id, title, stars) values (759, 'Caçapava', 1.5);
insert into TravelReview (id, title, stars) values (760, 'Dongen', 4.4);
insert into TravelReview (id, title, stars) values (761, 'Sukhothai', 1.7);
insert into TravelReview (id, title, stars) values (762, 'Mandalasari', 1.4);
insert into TravelReview (id, title, stars) values (763, 'Myitkyina', 1.9);
insert into TravelReview (id, title, stars) values (764, 'Ejidal', 3.2);
insert into TravelReview (id, title, stars) values (765, 'Anserma', 3.0);
insert into TravelReview (id, title, stars) values (766, 'Calauag', 4.9);
insert into TravelReview (id, title, stars) values (767, 'Napoles', 4.7);
insert into TravelReview (id, title, stars) values (768, 'Barcelona', 3.5);
insert into TravelReview (id, title, stars) values (769, 'Jiakexi', 1.9);
insert into TravelReview (id, title, stars) values (770, 'Qijiawan', 3.5);
insert into TravelReview (id, title, stars) values (771, 'Ar Ru’ays', 1.7);
insert into TravelReview (id, title, stars) values (772, 'San Pedro Jocopilas', 2.7);
insert into TravelReview (id, title, stars) values (773, 'Tangguhang', 1.4);
insert into TravelReview (id, title, stars) values (774, 'Libacao', 2.4);
insert into TravelReview (id, title, stars) values (775, 'Temanjang', 3.4);
insert into TravelReview (id, title, stars) values (776, 'Situsari', 2.5);
insert into TravelReview (id, title, stars) values (777, 'Huibu', 4.9);
insert into TravelReview (id, title, stars) values (778, 'Växjö', 2.9);
insert into TravelReview (id, title, stars) values (779, 'Guanshan', 4.6);
insert into TravelReview (id, title, stars) values (780, 'Lumil', 1.2);
insert into TravelReview (id, title, stars) values (781, 'Lingquan', 4.2);
insert into TravelReview (id, title, stars) values (782, 'Kāleke Mandi', 2.2);
insert into TravelReview (id, title, stars) values (783, 'Mačkovec', 3.9);
insert into TravelReview (id, title, stars) values (784, 'Shigongqiao', 2.4);
insert into TravelReview (id, title, stars) values (785, 'Pau', 3.2);
insert into TravelReview (id, title, stars) values (786, 'Khamis Mushait', 1.0);
insert into TravelReview (id, title, stars) values (787, 'Glugur Tengah', 2.1);
insert into TravelReview (id, title, stars) values (788, 'Sufang', 3.8);
insert into TravelReview (id, title, stars) values (789, 'Venustiano Carranza', 2.3);
insert into TravelReview (id, title, stars) values (790, 'Milanówek', 3.2);
insert into TravelReview (id, title, stars) values (791, 'Comodoro Rivadavia', 1.8);
insert into TravelReview (id, title, stars) values (792, 'Nanyang', 3.0);
insert into TravelReview (id, title, stars) values (793, 'Huayang', 1.2);
insert into TravelReview (id, title, stars) values (794, 'El Paso', 4.5);
insert into TravelReview (id, title, stars) values (795, 'Dongxi', 2.5);
insert into TravelReview (id, title, stars) values (796, 'Lianozovo', 1.1);
insert into TravelReview (id, title, stars) values (797, 'Munkfors', 4.9);
insert into TravelReview (id, title, stars) values (798, 'Santa Luzia', 2.5);
insert into TravelReview (id, title, stars) values (799, 'Yambio', 4.5);
insert into TravelReview (id, title, stars) values (800, 'Magersari', 1.3);
insert into TravelReview (id, title, stars) values (801, 'Krasnoye', 2.5);
insert into TravelReview (id, title, stars) values (802, 'Lacdayan', 3.6);
insert into TravelReview (id, title, stars) values (803, 'Ostojićevo', 3.3);
insert into TravelReview (id, title, stars) values (804, 'Avignon', 1.2);
insert into TravelReview (id, title, stars) values (805, 'Yezhou', 4.6);
insert into TravelReview (id, title, stars) values (806, 'Tbêng Méanchey', 1.7);
insert into TravelReview (id, title, stars) values (807, 'Magisterial', 2.7);
insert into TravelReview (id, title, stars) values (808, 'Dunmanway', 2.9);
insert into TravelReview (id, title, stars) values (809, 'Trzebinia', 1.4);
insert into TravelReview (id, title, stars) values (810, 'Radenković', 3.4);
insert into TravelReview (id, title, stars) values (811, 'Fengcheng', 1.2);
insert into TravelReview (id, title, stars) values (812, 'Puerto San José', 1.5);
insert into TravelReview (id, title, stars) values (813, 'Višňova', 2.2);
insert into TravelReview (id, title, stars) values (814, 'Xin’an', 3.4);
insert into TravelReview (id, title, stars) values (815, 'Gornje Moštre', 1.9);
insert into TravelReview (id, title, stars) values (816, 'Pasirjengkol', 1.6);
insert into TravelReview (id, title, stars) values (817, 'Oslo', 4.9);
insert into TravelReview (id, title, stars) values (818, 'Aş Şūrah aş Şaghīrah', 3.5);
insert into TravelReview (id, title, stars) values (819, 'Orhei', 2.5);
insert into TravelReview (id, title, stars) values (820, 'Sudzha', 3.8);
insert into TravelReview (id, title, stars) values (821, 'Orhon', 4.6);
insert into TravelReview (id, title, stars) values (822, 'Central', 3.9);
insert into TravelReview (id, title, stars) values (823, 'Shuyuan', 2.6);
insert into TravelReview (id, title, stars) values (824, 'Ilha Solteira', 4.6);
insert into TravelReview (id, title, stars) values (825, 'Satu Nou', 2.7);
insert into TravelReview (id, title, stars) values (826, 'Östersund', 3.2);
insert into TravelReview (id, title, stars) values (827, 'Carquefou', 1.4);
insert into TravelReview (id, title, stars) values (828, 'Jialu', 4.4);
insert into TravelReview (id, title, stars) values (829, 'Zhangpu', 2.4);
insert into TravelReview (id, title, stars) values (830, 'San Miguel', 2.5);
insert into TravelReview (id, title, stars) values (831, 'Osasco', 2.2);
insert into TravelReview (id, title, stars) values (832, 'Cabangahan', 3.9);
insert into TravelReview (id, title, stars) values (833, 'Ashford', 4.0);
insert into TravelReview (id, title, stars) values (834, 'Briceni', 4.0);
insert into TravelReview (id, title, stars) values (835, 'Huzhuang', 3.8);
insert into TravelReview (id, title, stars) values (836, 'Osias', 4.9);
insert into TravelReview (id, title, stars) values (837, 'Saijō', 2.4);
insert into TravelReview (id, title, stars) values (838, 'Mollepampa', 4.5);
insert into TravelReview (id, title, stars) values (839, 'Brumado', 1.5);
insert into TravelReview (id, title, stars) values (840, 'Cimuncang', 2.1);
insert into TravelReview (id, title, stars) values (841, 'Kurbnesh', 2.3);
insert into TravelReview (id, title, stars) values (842, 'Muzhou', 2.5);
insert into TravelReview (id, title, stars) values (843, 'Marićka', 3.0);
insert into TravelReview (id, title, stars) values (844, 'Kraljevica', 2.6);
insert into TravelReview (id, title, stars) values (845, 'Ala', 4.2);
insert into TravelReview (id, title, stars) values (846, 'Mariquita', 3.9);
insert into TravelReview (id, title, stars) values (847, 'Srinjine', 1.7);
insert into TravelReview (id, title, stars) values (848, 'Vidnoye', 4.7);
insert into TravelReview (id, title, stars) values (849, 'Tabanan', 1.3);
insert into TravelReview (id, title, stars) values (850, 'Valle de Guanape', 4.5);
insert into TravelReview (id, title, stars) values (851, 'Sandu', 4.8);
insert into TravelReview (id, title, stars) values (852, 'Urrao', 3.8);
insert into TravelReview (id, title, stars) values (853, 'Bulubrangsi', 2.4);
insert into TravelReview (id, title, stars) values (854, 'Shangchewan', 1.8);
insert into TravelReview (id, title, stars) values (855, 'Valença do Piauí', 1.8);
insert into TravelReview (id, title, stars) values (856, 'Lok', 1.1);
insert into TravelReview (id, title, stars) values (857, 'Petkovci', 1.4);
insert into TravelReview (id, title, stars) values (858, 'Laojun', 2.8);
insert into TravelReview (id, title, stars) values (859, 'Kovrov', 1.9);
insert into TravelReview (id, title, stars) values (860, 'Belyye Stolby', 2.1);
insert into TravelReview (id, title, stars) values (861, 'Pameče', 3.1);
insert into TravelReview (id, title, stars) values (862, 'Baki', 3.4);
insert into TravelReview (id, title, stars) values (863, 'Guanshui', 1.6);
insert into TravelReview (id, title, stars) values (864, 'Jönköping', 4.0);
insert into TravelReview (id, title, stars) values (865, 'Крива Паланка', 3.7);
insert into TravelReview (id, title, stars) values (866, 'Smiřice', 2.3);
insert into TravelReview (id, title, stars) values (867, 'Bangad', 1.3);
insert into TravelReview (id, title, stars) values (868, 'Laguna Limpia', 1.1);
insert into TravelReview (id, title, stars) values (869, 'Além', 3.5);
insert into TravelReview (id, title, stars) values (870, 'Vodyane', 4.9);
insert into TravelReview (id, title, stars) values (871, 'Beibao', 3.1);
insert into TravelReview (id, title, stars) values (872, 'Chipoka', 2.7);
insert into TravelReview (id, title, stars) values (873, 'Černá Hora', 1.9);
insert into TravelReview (id, title, stars) values (874, 'Wanghu', 4.5);
insert into TravelReview (id, title, stars) values (875, 'Hongtang', 4.8);
insert into TravelReview (id, title, stars) values (876, 'Sandao', 1.1);
insert into TravelReview (id, title, stars) values (877, 'Isanlu Itedoijowa', 4.2);
insert into TravelReview (id, title, stars) values (878, 'Quimper', 4.1);
insert into TravelReview (id, title, stars) values (879, 'Sung Noen', 3.0);
insert into TravelReview (id, title, stars) values (880, 'Jianguo', 1.7);
insert into TravelReview (id, title, stars) values (881, 'Kilcullen', 2.5);
insert into TravelReview (id, title, stars) values (882, 'Xiaoyan', 4.1);
insert into TravelReview (id, title, stars) values (883, 'Umeå', 1.8);
insert into TravelReview (id, title, stars) values (884, 'Yarumal', 3.1);
insert into TravelReview (id, title, stars) values (885, 'Nianqiao', 1.4);
insert into TravelReview (id, title, stars) values (886, 'Sanhe', 3.1);
insert into TravelReview (id, title, stars) values (887, 'Embalse', 1.4);
insert into TravelReview (id, title, stars) values (888, 'Xinji', 3.7);
insert into TravelReview (id, title, stars) values (889, 'Kokubunji', 4.3);
insert into TravelReview (id, title, stars) values (890, 'Luci', 5.0);
insert into TravelReview (id, title, stars) values (891, 'Kobiernice', 3.2);
insert into TravelReview (id, title, stars) values (892, 'Sundbyberg', 3.6);
insert into TravelReview (id, title, stars) values (893, 'Drobin', 2.1);
insert into TravelReview (id, title, stars) values (894, 'Stronie', 2.2);
insert into TravelReview (id, title, stars) values (895, 'Şafwá', 4.2);
insert into TravelReview (id, title, stars) values (896, 'Cariaco', 2.3);
insert into TravelReview (id, title, stars) values (897, 'Klimovsk', 4.1);
insert into TravelReview (id, title, stars) values (898, 'Michałów-Reginów', 3.0);
insert into TravelReview (id, title, stars) values (899, 'Oitui', 4.0);
insert into TravelReview (id, title, stars) values (900, 'Dobropillya', 1.3);
insert into TravelReview (id, title, stars) values (901, 'Makbon', 2.8);
insert into TravelReview (id, title, stars) values (902, 'Bendungan', 1.1);
insert into TravelReview (id, title, stars) values (903, 'Žulová', 2.9);
insert into TravelReview (id, title, stars) values (904, 'Bang Sao Thong', 2.8);
insert into TravelReview (id, title, stars) values (905, 'Kowale Oleckie', 3.7);
insert into TravelReview (id, title, stars) values (906, 'Binhailu', 4.2);
insert into TravelReview (id, title, stars) values (907, 'Fengshan', 4.1);
insert into TravelReview (id, title, stars) values (908, 'Xilópolis', 1.3);
insert into TravelReview (id, title, stars) values (909, 'Chamouny', 3.5);
insert into TravelReview (id, title, stars) values (910, 'Nikolayevka', 1.3);
insert into TravelReview (id, title, stars) values (911, 'Iparia', 3.2);
insert into TravelReview (id, title, stars) values (912, 'Naftalan', 1.4);
insert into TravelReview (id, title, stars) values (913, 'Lopez Jaena', 2.8);
insert into TravelReview (id, title, stars) values (914, 'Berbera', 1.9);
insert into TravelReview (id, title, stars) values (915, 'Gbarnga', 4.4);
insert into TravelReview (id, title, stars) values (916, 'Kanthararom', 4.6);
insert into TravelReview (id, title, stars) values (917, 'Kuala Baru', 2.2);
insert into TravelReview (id, title, stars) values (918, 'Неготино', 2.7);
insert into TravelReview (id, title, stars) values (919, 'Choibalsan', 4.6);
insert into TravelReview (id, title, stars) values (920, 'Lianyuan', 2.7);
insert into TravelReview (id, title, stars) values (921, 'Karangasem Laok', 2.7);
insert into TravelReview (id, title, stars) values (922, 'Serdobsk', 1.8);
insert into TravelReview (id, title, stars) values (923, 'Pompéu', 4.0);
insert into TravelReview (id, title, stars) values (924, 'Małkinia Górna', 3.9);
insert into TravelReview (id, title, stars) values (925, 'Faya-Largeau', 3.6);
insert into TravelReview (id, title, stars) values (926, 'Langchi', 4.2);
insert into TravelReview (id, title, stars) values (927, 'Shujāābād', 1.8);
insert into TravelReview (id, title, stars) values (928, 'Meishan', 3.7);
insert into TravelReview (id, title, stars) values (929, 'Sechenovo', 2.7);
insert into TravelReview (id, title, stars) values (930, 'Saku', 3.9);
insert into TravelReview (id, title, stars) values (931, 'Gongli', 3.5);
insert into TravelReview (id, title, stars) values (932, 'General Viamonte', 4.8);
insert into TravelReview (id, title, stars) values (933, 'Zhendong', 1.1);
insert into TravelReview (id, title, stars) values (934, 'Caotang', 1.1);
insert into TravelReview (id, title, stars) values (935, 'Cut-cut Primero', 2.4);
insert into TravelReview (id, title, stars) values (936, 'Cochabamba', 2.8);
insert into TravelReview (id, title, stars) values (937, 'Santiago del Torno', 4.4);
insert into TravelReview (id, title, stars) values (938, 'Toyohama', 4.1);
insert into TravelReview (id, title, stars) values (939, 'Qŭshkŭpir', 1.9);
insert into TravelReview (id, title, stars) values (940, 'Jadi', 1.8);
insert into TravelReview (id, title, stars) values (941, 'Nakatsugawa', 4.6);
insert into TravelReview (id, title, stars) values (942, 'David', 4.7);
insert into TravelReview (id, title, stars) values (943, 'Yahe', 3.9);
insert into TravelReview (id, title, stars) values (944, 'Wa’erma', 4.6);
insert into TravelReview (id, title, stars) values (945, 'Bayog', 2.3);
insert into TravelReview (id, title, stars) values (946, 'Kota Kinabalu', 2.2);
insert into TravelReview (id, title, stars) values (947, 'Sandgerði', 2.3);
insert into TravelReview (id, title, stars) values (948, 'Pubal', 1.4);
insert into TravelReview (id, title, stars) values (949, 'Tân Phú', 2.7);
insert into TravelReview (id, title, stars) values (950, 'Pawing', 3.9);
insert into TravelReview (id, title, stars) values (951, 'Pringgabaya', 3.7);
insert into TravelReview (id, title, stars) values (952, 'Qingkenpao', 4.9);
insert into TravelReview (id, title, stars) values (953, 'Kannus', 3.4);
insert into TravelReview (id, title, stars) values (954, 'Oshawa', 3.2);
insert into TravelReview (id, title, stars) values (955, 'Timezgana', 2.7);
insert into TravelReview (id, title, stars) values (956, 'Cilangkap', 2.4);
insert into TravelReview (id, title, stars) values (957, 'Dugcal', 3.8);
insert into TravelReview (id, title, stars) values (958, 'Maguan', 4.9);
insert into TravelReview (id, title, stars) values (959, 'Staryye Atagi', 1.1);
insert into TravelReview (id, title, stars) values (960, 'Słupno', 2.3);
insert into TravelReview (id, title, stars) values (961, 'Meishan', 2.9);
insert into TravelReview (id, title, stars) values (962, 'Halinów', 4.0);
insert into TravelReview (id, title, stars) values (963, 'Fahraj', 2.6);
insert into TravelReview (id, title, stars) values (964, 'Xinxing', 2.9);
insert into TravelReview (id, title, stars) values (965, 'Duwaktenggi', 4.3);
insert into TravelReview (id, title, stars) values (966, 'Divo', 2.7);
insert into TravelReview (id, title, stars) values (967, 'Mhamid', 1.8);
insert into TravelReview (id, title, stars) values (968, 'Wangjiachang', 1.4);
insert into TravelReview (id, title, stars) values (969, 'Liping', 4.8);
insert into TravelReview (id, title, stars) values (970, 'Tangzhuang', 3.7);
insert into TravelReview (id, title, stars) values (971, 'Colos', 4.0);
insert into TravelReview (id, title, stars) values (972, 'Kineshma', 3.1);
insert into TravelReview (id, title, stars) values (973, 'Xingcheng', 3.3);
insert into TravelReview (id, title, stars) values (974, 'Laocheng', 1.9);
insert into TravelReview (id, title, stars) values (975, 'Ta’ Xbiex', 1.5);
insert into TravelReview (id, title, stars) values (976, 'Shaoyang', 2.6);
insert into TravelReview (id, title, stars) values (977, 'Yalkhoy-Mokhk', 4.5);
insert into TravelReview (id, title, stars) values (978, 'Trollhättan', 3.3);
insert into TravelReview (id, title, stars) values (979, 'Lingdangge', 2.0);
insert into TravelReview (id, title, stars) values (980, 'Kedian', 2.6);
insert into TravelReview (id, title, stars) values (981, 'Lianghe', 3.1);
insert into TravelReview (id, title, stars) values (982, 'Daduchuan', 3.4);
insert into TravelReview (id, title, stars) values (983, 'Muli', 3.9);
insert into TravelReview (id, title, stars) values (984, 'Koa', 1.2);
insert into TravelReview (id, title, stars) values (985, 'Deqing', 4.9);
insert into TravelReview (id, title, stars) values (986, 'Kvasice', 2.3);
insert into TravelReview (id, title, stars) values (987, 'Yihe', 4.2);
insert into TravelReview (id, title, stars) values (988, 'Mazha', 1.9);
insert into TravelReview (id, title, stars) values (989, 'Alberton', 4.3);
insert into TravelReview (id, title, stars) values (990, 'Wuyanquan', 4.6);
insert into TravelReview (id, title, stars) values (991, 'Rudolfov', 1.6);
insert into TravelReview (id, title, stars) values (992, 'Arras', 2.7);
insert into TravelReview (id, title, stars) values (993, 'Huangshi', 2.6);
insert into TravelReview (id, title, stars) values (994, 'Koška', 3.9);
insert into TravelReview (id, title, stars) values (995, 'Shanban', 4.0);
insert into TravelReview (id, title, stars) values (996, 'Don Matías', 3.5);
insert into TravelReview (id, title, stars) values (997, 'Bilao', 3.8);
insert into TravelReview (id, title, stars) values (998, 'Hengjing', 3.8);
insert into TravelReview (id, title, stars) values (999, 'Hartford', 4.1);
insert into TravelReview (id, title, stars) values (1000, 'Bago', 4.9);
